task_1_3_1
KozlovKV/OOP pull request #10
Opened 2023-11-03 15:46 UTC by KozlovKV

Черновая версия с не самым эффективным алгоритмом

2023-11-03 15:55 UTC, KozlovKV commented
Очень странно, но компилятор на сервере не может найти метод `isEmpty()` для `StringBuffer`, хотя локально он находится без проблем

2023-11-04 08:02 UTC, galinabykova requested changes
ещё нужно читать файлы из ресурсов, подробнее написала в телеграмме

2023-11-04 08:02 UTC, galinabykova commented on task_1_3_1/data/tests_generator.py
Хочется, чтобы при достаточном количестве выделенных ресурсов на сервере, этот тест можно было автоматически запустить без каких-либо дополнительных действий. Я предполагала, что этот файл будет сначала создаваться в тесте, потом для него будет запускаться алгоритм, потом он будет удаляться

2023-11-04 10:58 UTC, KozlovKV commented on task_1_3_1/data/tests_generator.py
Почитал статью, которую ты скидывала, посмотрел в других источниках в интернете и выглядит всё так, будто бы не очень рекомендуется писать что-то в `resources`. В частности, я вообще не нашёл возможности не костыльного создания файла в папке ресурсов и открытия его в `OutputStream`. Наверное, костылями можно это сделать (либо ещё более костыльно - запустить из Java питоновский скрипт - но это, скорее всего, надо менять код в workflow, а это вряд ли разрешено), но не уверен, что стоит. Если всё же надо, то продолжу искать решение

2023-11-04 11:01 UTC, galinabykova commented on task_1_3_1/data/tests_generator.py
Не, не, это не надо в ресурсы

2023-11-04 11:03 UTC, galinabykova commented on task_1_3_1/data/tests_generator.py
Я имела ввиду, что в ресурсы уже готовые файлики надо добавлять, а генерируемые не надо, там вроде и не должно быть проблем с путями, где создал, там же прочёл и удалил

2023-11-04 11:05 UTC, galinabykova commented on task_1_3_1/data/tests_generator.py
но сформулировала криво, да

2023-11-04 11:37 UTC, galinabykova commented on task_1_3_1/src/main/java/kozlov/kirill/finders/SimpleStringFinder.java
> +    public void findingCycle() {
Кажется, ты здесь забыл поменять модификатор доступа

2023-11-04 11:37 UTC, galinabykova commented on task_1_3_1/data/tests_generator.py
Я думала, что этот тест будет выглядеть примерно так:
1. С помощью какого-нибудь Writer пишем в файл на джава
2. Ищем построки в этом файла
3. Удаляем файл

2023-11-04 11:38 UTC, galinabykova commented on task_1_3_1/data/tests_generator.py
А, до меня дошло, почему возникла проблема

2023-11-04 11:51 UTC, galinabykova commented on task_1_3_1/data/tests_generator.py
Можно сделать так, чтобы алгоритм работал с InputStream, а чтение из ресурсов/чтение из "обычного" файла делать в тестах/main (мне этот вариант больше нравится). Или искать файл сначала в ресурсах, потом в файловой системе. Вообще только сейчас заметила, что мы делаем не библиотеку, а консольное приложение.

2023-11-04 13:31 UTC, galinabykova commented on task_1_3_1/data/tests_generator.py
Можно сделать функцию, которая будет принимать InputStream, и тестировать для этой функции интересные случаи и т.д. А find будет вызывать эту функцию, для find можно написать один тест со сгенерированным файликом.

2023-11-04 16:46 UTC, KozlovKV commented on task_1_3_1/data/tests_generator.py
Сначала написал смешанную версию для чтения сначала из ресурсов, а потом, если там ничего нет, из другого пути, но потом таки понял, в чём смысл этой папки и создал разделённую версию

2023-11-04 16:47 UTC, KozlovKV commented
Интересно, Гитхаб вообще выделит столько места...

2023-11-04 16:50 UTC, KozlovKV commented
Ух ты! Он вывез

2023-11-04 18:34 UTC, galinabykova requested changes

2023-11-04 18:34 UTC, galinabykova commented on task_1_3_1/src/main/java/kozlov/kirill/finders/StringFinder.java
> +            throw new RuntimeException(e);
Считается, что RuntimeException не надо ловить. Их обычно бросают, если исключение нормально никак не обработать, точно нужно завершать программу. Такая ли у тебя ситуация здесь?

2023-11-05 07:00 UTC, galinabykova approved these changes

2023-11-05 09:33 UTC, merged