task_1_4_1
KozlovKV/OOP pull request #11
Opened 2023-11-14 13:04 UTC by KozlovKV

2023-11-14 14:08 UTC, galinabykova commented
> Обидно, что в версии Java на Гитхабе `record` не поддерживается (

по идее где-то в настройках gradle должна быть возможность указать, какую версию ты хочешь использовать.

https://docs.gradle.org/current/userguide/toolchains.html

Может быть так, но я не уверена

2023-11-14 15:52 UTC, KozlovKV commented
Ладно, тут уже мигрировал на прежнюю версию класса и большого смысла перенастраивать градл не вижу. Просто оставлю себе в конспекте пометку о таком синтаксическом сахаре. Вроде бы всё готово (даже смог в этот раз разобраться с замечанием по стилю по поводу отступов в докстрингах) )

2023-11-15 05:30 UTC, galinabykova requested changes

2023-11-15 05:30 UTC, galinabykova commented on task_1_4_1/src/main/java/kozlov/kirill/creditbook/Student.java
> +        private static final double MIN_AVG_FOR_RED_DIPLOMA = 4.75 - 0.000000001;
а зачем тут - 0.000000001?

2023-11-15 05:30 UTC, galinabykova commented on task_1_4_1/src/main/java/kozlov/kirill/creditbook/Student.java
> +                if (prevMark != null && prevMark.getSemester() < mark.getSemester()
можно было бы, наверно, сделать отдельный метод в Mark, является ли одна Mark более поздней по тому же предмету, тогда это условие будет проще читаться

2023-11-15 05:30 UTC, galinabykova commented on task_1_4_1/src/main/java/kozlov/kirill/creditbook/Student.java
> +        public boolean canObtainRedDiploma() {
в условии указано, что нужно вычислять **возможность** получения «красного» диплома с отличием. Мне кажется, что это значит, что нужно определять, имеет ли возможность студент получить красный диплом в будущем или это условие безнадёжно утрачено. Скажем, если студент получил тройку, то всё, ничего нельзя сделать. А если у него стоит 4 четвёрки, а всего предметов 17, то ещё не всё потеряно, можно сдать остальное на 5 и получить красный диплом

2023-11-15 15:15 UTC, KozlovKV commented on task_1_4_1/src/main/java/kozlov/kirill/creditbook/Student.java
> +        private static final double MIN_AVG_FOR_RED_DIPLOMA = 4.75 - 0.000000001;
Вроде ж это классическая штука для плавающих чисел? Теоретически, у нас может при делении возникнуть значение `4.7499999999999...` и оно должно также засчитаться

2023-11-15 15:23 UTC, galinabykova commented on task_1_4_1/src/main/java/kozlov/kirill/creditbook/Student.java
> +        private static final double MIN_AVG_FOR_RED_DIPLOMA = 4.75 - 0.000000001;
О, точно, забыла)

2023-11-17 11:09 UTC, KozlovKV commented on task_1_4_1/src/main/java/kozlov/kirill/creditbook/Student.java
> +        public boolean canObtainRedDiploma() {
Справедливо

2023-11-17 15:22 UTC, galinabykova approved these changes

2023-11-17 16:06 UTC, merged