task_2_1_1
KozlovKV/OOP pull request #13
Opened 2024-02-09 13:28 UTC by KozlovKV

2024-02-09 15:42 UTC, KozlovKV commented
Вроде бы готово. Пока что не проводил подробные замеры с составлением графиков (только небольшой коммент в мэйне). Потом тебе графики отправить в Телеге или просто при очной сдаче покзаать?

2024-02-09 16:15 UTC, galinabykova commented
> Вроде бы готово. Пока что не проводил подробные замеры с составлением графиков (только небольшой коммент в мэйне). Потом тебе графики отправить в Телеге или просто при очной сдаче покзаать?

Графики нужно загрузить в репозиторий

2024-02-09 18:10 UTC, galinabykova requested changes

2024-02-10 07:33 UTC, KozlovKV commented on task_2_1_1/src/main/java/kozlov/kirill/primes/Main.java
> +            list.add(100000007);
Настолько магическое, что я перепутал число нулей, но чудом оно тоже оказалось простым XD
Исправил

2024-02-10 07:36 UTC, KozlovKV commented on task_2_1_1/src/main/java/kozlov/kirill/primes/ThreadUnprimeChecker.java
> +        final int threadNumberListSize = numbersSize / threadsCount + 1;
Да. Сначала пытался сделать округление вверх, но ceilDiv не хотел адекватно работать, поэтому решил сделать такой мини-костыль. Думаю, что такой вариант не хуже добавления хвоста к последнему потоку, потому что в среднем распределение будет более равномерным (если добавлять остаток к последнему для 19 чисел, то будет 4, 4, 4, 7, а у меня - 5, 5, 5, 4). Ну и для большой длины массива выбор метода будто бы становится несущественным

2024-02-10 07:37 UTC, KozlovKV commented on task_2_1_1/src/main/java/kozlov/kirill/primes/UnprimeChecker.java
> +    ArrayList<Integer> numbers = new ArrayList<>();
Была такая мысль, но я решил "А вдруг гипотетический пользователь захочет сделать свою реализацию"

2024-02-10 07:43 UTC, KozlovKV commented on task_2_1_1/src/main/java/kozlov/kirill/primes/UnprimeChecker.java
> +    protected boolean isNumUnprime(Integer num) {
Вроде по определению простые числа натуральные... В таком случае 2 варианта: считать правильность по модулю либо считать все ненатуральные числа неправильными. Мне кажется более правильным первый вариант, но не пртетендуею на правоту.
Кстати, вот какой ещё интересный вопрос: а 0 - это какое число?

2024-02-10 11:38 UTC, galinabykova commented on task_2_1_1/src/main/java/kozlov/kirill/primes/UnprimeChecker.java
> +    protected boolean isNumUnprime(Integer num) {
Да, по определению простые числа натуральные. Я бы тоже не стала претендовать на правоту в том, что делать с отрицательными числами, но у тебя вот эта функция принимает массив целых чисел, среди которых может быть 0 или отрицательное число. И есть несколько вариантов, как ты можешь действовать в этом случае: можно проверять, что числа положительные, и если это не так, кидать исключение, но такие проверки будут занимать время. Если это критично, можно в документации явно прописать, что функция принимает ТОЛЬКО ПОЛОЖИТЕЛЬНЫЕ числа, и если это не так - это не твои проблемы. Можно прописать, в документации, что с отрицательными числами функция ведёт себя вот так. Любой из этих вариантов имеет право на существование, сделай, как тебе больше нравится. У меня этот вопрос возник потому, что в текущей реализации у тебя любое отрицательное число и 0 - это не непростое число, то есть простое.

2024-02-10 12:00 UTC, galinabykova commented on task_2_1_1/src/main/java/kozlov/kirill/primes/ThreadUnprimeChecker.java
> +        final int threadNumberListSize = numbersSize / threadsCount + 1;
вот это утверждение `для большой длины массива выбор метода будто бы становится несущественным` зависит от того, насколько большие числа, принимает на вход твоя программа. Твоя функция работает с Integer, на одно число максимум 50 000 итераций, домножим на число потоков как максимальную разницу. Хорошо, аргумент принимается, переделывать не надо)

на всякий случай проговорю (вдруг ты не заметил), что на паре я добавляла не в хвост, а распределяла по потокам остаток. Соглашусь, что все эти формулки на практике не всегда имеет смысл использовать (в моём примере, наверно, они всё-таки были лишние). Но если задач, которые ты распределяешь между потоками будет немного, но при этом каждая из них будет трудоёмкая - ситуация кардинально поменяется.

2024-02-10 12:17 UTC, galinabykova commented on task_2_1_1/src/main/java/kozlov/kirill/primes/UnprimeChecker.java
> +    ArrayList<Integer> numbers = new ArrayList<>();
а тут не наоборот? гипотетический пользователь захочет сделать реализацию в другом пакете и массив с видимостью default не увидит

2024-02-10 12:18 UTC, galinabykova requested changes
ещё график нужно

2024-02-10 17:54 UTC, KozlovKV commented on task_2_1_1/src/main/java/kozlov/kirill/primes/UnprimeChecker.java
> +    ArrayList<Integer> numbers = new ArrayList<>();
Ааа! Тут речь была о массиве. Я просто решил, что речь о самом классе

2024-02-10 19:27 UTC, KozlovKV commented
Теперь вроде бы всё. Решил ещё вычислить самое удачное количество потоков. Как и предполагал, быстрее всего будет работать с количеством потоков, равным количеству потоков процессора

2024-02-11 05:35 UTC, galinabykova approved these changes

2024-02-13 02:52 UTC, merged