task_2_1_2
KozlovKV/OOP pull request #14
Opened 2024-03-03 08:32 UTC by KozlovKV

Привет. Вот первая версия решения. Из того, что планирую сделать точно - более умная обработка различных ошибок + отправка сообщений пользователю (пока что они малоинформативные)

Ещё думаю разделить `Manager` на несколько классов, чтобы он занимался только приёмом данных от пользователя, а потом запускал поток с вычислителем, который либо сам будет отправлять пользователю результат, либо скажет отправить результат ещё одному классу (aka курьеру)

А вот с чем возникли большие проблемы и для чего решения я пока не нашёл - это как мне сделать поиск сервера по подсети. Дело в том, что broadcast идёт по всем адресам локалки, но лишь по конкретному порту, а у нас все узлы реально сидят на одной машине, но на разных портах, из-за этого надо либо достать где-то ещё компов для работы этого механизма, либо как-то сильно заморочиться с виртуалками или контейнерами, либо делать слушатель по конкретному адресу на всех портах, что... Криво и оторвано от реальности, что ли... Пока что остановился на простом TCP с заранее известными портами. Какой вариант следует выбрать?

2024-03-03 08:48 UTC, KozlovKV commented
Добавил в `README.md` описание акутальной реализации и кое-какие мысли по её модификации

2024-03-04 13:46 UTC, KozlovKV commented
Разделил функционал менеджера на, собственно, менеджера и воркера. Потестил с отправкой сотни запросов - вроде всё работает. через утилиту `nc` тоже могу по локалке обращаться.

Теперь 2 вопроса:
1. Вроде как все потоки, которые должны умереть, умирают, однако полной уверенности нет. Можешь посоветовать инструменты для просмотра времени работы потоков? (сейчас пользуюсь VisualVM, но может у тебя на примете есть что-то ещё)
2. Какие виды тестов надо для всего этого делать?

2024-03-04 16:40 UTC, galinabykova commented
> Привет. Вот первая версия решения. Из того, что планирую сделать точно - более умная обработка различных ошибок + отправка сообщений пользователю (пока что они малоинформативные)
> 
> Ещё думаю разделить `Manager` на несколько классов, чтобы он занимался только приёмом данных от пользователя, а потом запускал поток с вычислителем, который либо сам будет отправлять пользователю результат, либо скажет отправить результат ещё одному классу (aka курьеру)
> 
> А вот с чем возникли большие проблемы и для чего решения я пока не нашёл - это как мне сделать поиск сервера по подсети. Дело в том, что broadcast идёт по всем адресам локалки, но лишь по конкретному порту, а у нас все узлы реально сидят на одной машине, но на разных портах, из-за этого надо либо достать где-то ещё компов для работы этого механизма, либо как-то сильно заморочиться с виртуалками или контейнерами, либо делать слушатель по конкретному адресу на всех портах, что... Криво и оторвано от реальности, что ли... Пока что остановился на простом TCP с заранее известными портами. Какой вариант следует выбрать?

Привет, я сейчас попробовала создать пример, в котором разные потоки слушали на одном и том же широковещательном адресе и порту, и все они получили отправленное сообщение. Дело в том, что шировещательность - это не свойство сокета или соединения, это свойство адреса. Все устройства в сети должны интерпретировать широковещательный адрес как свой собственный.

2024-03-04 18:20 UTC, galinabykova commented
> Разделил функционал менеджера на, собственно, менеджера и воркера. Потестил с отправкой сотни запросов - вроде всё работает. через утилиту `nc` тоже могу по локалке обращаться.
> 
> Теперь 2 вопроса:
> 
>     1. Вроде как все потоки, которые должны умереть, умирают, однако полной уверенности нет. Можешь посоветовать инструменты для просмотра времени работы потоков? (сейчас пользуюсь VisualVM, но может у тебя на примете есть что-то ещё)
> 
>     2. Какие виды тестов надо для всего этого делать?

1. Нет, к сожалению, я вообще ничем таким не пользовалась
2. Модульные и интеграционные. Тесты лучше писать во время написания кода, чтобы при добавлении новых фич следить, что старые не сломались. В этой лабе тебе нужно сделать как обычно тесты на работу функций, а также тесты с непосредственно сетевым взаимодейтсвием с помощью потоков или процессов: базовый сценарий, падение одного из вычислительных узлов и тд

2024-03-05 02:30 UTC, galinabykova requested changes
Привет, мне понравилось, как ты вынес сериализацию в отдельный класс. Если я правильно поняла, у тебя в текущей реализации основное общение происходит между клиетом и менеджером, а вычислительные узлы запускаются в потоках. Если это временно, то всё хорошо, но на всяких случай уточню, что мы предполагаем, что вычислительные узлы могут быть на разных узлах, и в подсети мы как раз ищем все такие узлы.

2024-03-05 02:30 UTC, galinabykova commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/Manager.java
> +            new Thread(new Worker(socket, taskData.numbers()), "Worker").start();
почему ты решил вот тут отправлять потоки в свободное плавание?

2024-03-05 02:30 UTC, galinabykova commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/BasicTCPSocketOperations.java
> +            sendJSONObject(socket, errorMessage);
здесь ты предполагаешь, что в строчках 

```java
ObjectMapper mapper = new ObjectMapper();
            var parser = mapper.createParser(
                    new BufferedReader(new InputStreamReader(
                            socket.getInputStream(), StandardCharsets.UTF_8
                    ))
            );
            return parser.readValueAs(type);
```

IOException бросится только если был неправильный запрос? Если да, обоснуй, пожалуйста, если нет, объясни, почему такая обработка ошибок

2024-03-05 09:51 UTC, KozlovKV commented
> > Привет. Вот первая версия решения. Из того, что планирую сделать точно - более умная обработка различных ошибок + отправка сообщений пользователю (пока что они малоинформативные)
> > 
> > Ещё думаю разделить `Manager` на несколько классов, чтобы он занимался только приёмом данных от пользователя, а потом запускал поток с вычислителем, который либо сам будет отправлять пользователю результат, либо скажет отправить результат ещё одному классу (aka курьеру)
> > 
> > А вот с чем возникли большие проблемы и для чего решения я пока не нашёл - это как мне сделать поиск сервера по подсети. Дело в том, что broadcast идёт по всем адресам локалки, но лишь по конкретному порту, а у нас все узлы реально сидят на одной машине, но на разных портах, из-за этого надо либо достать где-то ещё компов для работы этого механизма, либо как-то сильно заморочиться с виртуалками или контейнерами, либо делать слушатель по конкретному адресу на всех портах, что... Криво и оторвано от реальности, что ли... Пока что остановился на простом TCP с заранее известными портами. Какой вариант следует выбрать?
> 
> Привет, я сейчас попробовала создать пример, в котором разные потоки слушали на одном и том же широковещательном адресе и порту, и все они получили отправленное сообщение. Дело в том, что шировещательность - это не свойство сокета или соединения, это свойство адреса. Все устройства в сети должны интерпретировать широковещательный адрес как свой собственный.

Если честно, не вполне понимаю, как это работает... То есть мы можем все свободные узлы ставить на получение UDP по одному и тому же порту, потом они все попытаются отправить ответ отправителю бродкаст-пакета, который будет содержать порт их серверного сокета, а затем отправитель бродкаста сможет связаться индивидуально с тем узлом, от которого он получил ответ?

2024-03-05 09:54 UTC, KozlovKV commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/Manager.java
> +            new Thread(new Worker(socket, taskData.numbers()), "Worker").start();
Основная цель воркера – сделать полезные расчёты и отправить результат пользователю. В случае какой-либо проблемы воркер сам о ней сообщит и должны образом прореагирует. Цель менеджера – просто принять покет, отвалидировать его немного и передать дальше. Это заодно позволит нам в рамках одного TCP-соединения отправлять много задач

2024-03-05 10:55 UTC, galinabykova commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/Manager.java
> +            new Thread(new Worker(socket, taskData.numbers()), "Worker").start();
Мне кажется, что здесь плохо, что ты больше не имеешь связи с потоком и при необходимости не можешь ему сказать что-то вроде: "хей, нам пришёл сигнал, что пора закругляться, подготовься к смерти" и т.д. А тебе надо уметь корректно завершать работу всей программы при необходимости.

Ещё опасно, что ты теряешь знание о том, сколько у тебя запущено потоков. Не могут ли у тебя все потоки забиться мёртвыми соединениями? Если бы в Java были виртуальные потоки, это было бы нормально, в языках со всякими корутинами и виртуальными потоками примерно так и делают (и это прекрасно), но потоки операционной системы затратны (а в джава такие), и их хочется контролировать, или иметь какой-то таймаут для отправки результата, чтобы быть уверенным, что после расчётов поток быстро завершится, или использовать пул потоков.

2024-03-06 16:07 UTC, KozlovKV commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/Gateway.java
> +        new Thread(new UDPReceiver(port), "UDP receiver for gateway on port " + port).start();
Вот здесь при попытке передать порт `BROADCAST_PORT` и количестве вызовов конструктора > 1, получаю ошибку. Если поставить создание `UDPReceiver`а в `run()`, то ничего не меняется

2024-03-06 16:10 UTC, KozlovKV commented
@galinabykova , привет! Попытался использовать UDP-сокеты с одним портом во множестве потоков и получил ошибку. Наверное я чего-то не понял относительно этого типа сокетов в целом, потому что ничего об этом в интернете не нашёл. Получается, я вообще не могу все узлы заставить слушать один и тот же порт, чтобы через него они могли понять, что кто-то ищет вычислительный узел. Если я передаю один и тот же UDP-сокет во все потоки, то пакет из него получит только один поток, а не все...

2024-03-09 08:06 UTC, KozlovKV commented
@galinabykova , привет. Вроде бы сделал новую версию, соответствующую условиям задачи.

Новое описание архитектуры сети в `README.md`.

Скажешь, подходит ли эта архитектура? Ну и может ещё какие-то замечания сразу будут (кое-что там уже пометил TODOшками). Замечания выше помню и тоже с оставшимися разберусь потом

2024-03-10 08:19 UTC, galinabykova commented
> @galinabykova , привет. Вроде бы сделал новую версию, соответствующую условиям задачи.
> 
> Новое описание архитектуры сети в `README.md`.
> 
> Скажешь, подходит ли эта архитектура? Ну и может ещё какие-то замечания сразу будут (кое-что там уже пометил TODOшками). Замечания выше помню и тоже с оставшимися разберусь потом

Привет, небольшое замечание по архитектуре. Это задача на распределённые вычисления и предполагается, что массив будет разделён на части, которые будут обрабатываться разными узлами. То есть тут тоже распараллеливание, но на разных вычислительных узлах

2024-03-10 15:03 UTC, KozlovKV commented
> > @galinabykova , привет. Вроде бы сделал новую версию, соответствующую условиям задачи.
> > Новое описание архитектуры сети в `README.md`.
> > Скажешь, подходит ли эта архитектура? Ну и может ещё какие-то замечания сразу будут (кое-что там уже пометил TODOшками). Замечания выше помню и тоже с оставшимися разберусь потом
> 
> Привет, небольшое замечание по архитектуре. Это задача на распределённые вычисления и предполагается, что массив будет разделён на части, которые будут обрабатываться разными узлами. То есть тут тоже распараллеливание, но на разных вычислительных узлах

Ну всё, вроде бы и это сделал

2024-03-14 09:08 UTC, galinabykova requested changes
У тебя получился довольно запутанный код, я долго пыталась осознать, что тут происходит. Скорее всего, основная причина в том, что ты не сразу верно понял условие, из-за этого код переделывался из раза в раз, каждый раз усложняясь. В этом во многом моя вина, потому что я в поездке не слишком вникала в твои вопросы. Я напишу тут вещи, которые меня смущают в текущей версии, но я не уверена, нужно ли их переделывать (потому что это займёт неприлично много времени). Я ожидаю, что что-то из этого ты сможешь частично переделать, про что-то просто напишешь, как это можно было бы сделать в твоей системе, если с чем-то не согласен, объяснишь почему.

Детали сетевой передачи данных содержатся практически в каждой части твоего кода. Это основная причина, почему тебе сложно написать юнит тесты: все части неразрывно связаны друг с другом, и ты можешь тестировать их только вместе, даже непонятно, что можно замокать. (Кстати, это одна из причин, почему писать тесты в процессе написания кода хорошая идея - часто (хотя и не всегда) продумывание "а как бы мне написать тут тест" заставляет тебя писать компоненты, менее зависимые друг от друга). Если бы у тебя были классы, которые, например, в конструкторе принимали какие-нибудь InputStream, OutputStream, ты бы мог их протестировать независимо друг от друга, проверяя в тесте, что вот на такой StringStream Worker реагирует вот так и т.д. И скорее всего такое разделение сделало бы код более читаемым: сейчас, чтобы понять, как он работает, мне нужно держать в голове несколько уровней абстракции одновременно (работа с сетью, какая-то бизнес-логика и т.д.).

Стандартное изменение в сетевых приложениях - поменять немного протокол взаимодействия. Можно ли в твоей системе достаточно безболезненно немного поменять данные? В текущей версии у тебя эта проблема отчасти снимается за счёт сериализации (можно добавить в соответствующий класс из data новую информацию), но если я захочу вместо TaskData передать что-то другое, мне придётся найти, где TaskData отправляется, читается, а потом ещё раз передаётся и ещё раз читается (проброс от Менеджера к Воркеру). Какие-то из этих мест найти относительно легко, потому что для них есть соответствующие функции, какие-то найти сложно, потому что передача происходит в функциях, которые делают что-то ещё. И про второй проброс достаточно легко забыть. Может, пример, достаточно искусственный, но основная идея в том, что тут всё та же проблема: сетевое взаимодействие пронизывает весь код.

Ещё мне всё же не нравится, что именно шлюз создаёт воркеров. Если это нужно только для тестов на локалхосте, лучше было написать создание воркеров на определённых портах в тестах.

Ещё забавно, что есть два куска кода, практически идентичных, но это, кажется, оправдано
![image](https://github.com/KozlovKV/OOP/assets/86754545/e5e079c2-b51b-4399-ba45-57f0fb9a80fd)
![image](https://github.com/KozlovKV/OOP/assets/86754545/57cab090-ac20-4b01-b2be-2bcdeadaa74e)

2024-03-15 15:15 UTC, KozlovKV commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/Gateway.java
> +        MulticastManager multicastManager = new MulticastManager("230.0.0.0", port);
Это временное решение. Дальше вынесу создание воркеров в какое-нибудь совершенно отдельное место

2024-03-15 15:16 UTC, KozlovKV commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/Gateway.java
> +                System.out.println("Connection to gateway from " + connectionSocket.getRemoteSocketAddress());
Не особо, насколько я помню

2024-03-15 15:17 UTC, KozlovKV commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/Gateway.java
> +                ); // TODO: перейти на виртуальные потоки
На последней лекции рассказали, что для создания клиентских штук каких-нибудь это достаточно хороший вариант, потому что будет куда легче для системы, на которой запущена программа. Однако для этого надо перейти аж на JDK 21, так что не уверен, что сделаю это

2024-03-15 19:02 UTC, KozlovKV commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/Manager.java
> +    private class MasterWorker implements Runnable {
Он достаточно тесно связан с менеджером, но наверное это само по себе не хорошо... Видимо мне предстоит мастабный рефакторинг

2024-03-15 19:04 UTC, KozlovKV commented on task_2_1_2/src/test/java/kozlov/kirill/UnitTest.java
Ух ты! Выходит я написал бОльшую часть интеграционных тестов. Это радует. Печалит, что для нормальных юнит-тестов много работы уйдёт, ведь, насколько я понял, если я буду делать юнит-тесты только для класса `UnprimeChecker`, этого будет недостаточно? Надо для всех компонентов, которые можно использовать без построения сети, написать такие тесты? А если компоненты не могут использоваться без сети, то это повод задуматься, а хорошо ли это

2024-03-15 19:18 UTC, galinabykova commented on task_2_1_2/src/test/java/kozlov/kirill/UnitTest.java
По идее да, надо для всех компонентов написать такие тесты) но там правда очень много работы уйдёт, так что смотри по нагрузке по другим предметам, я думаю, в учебных целях будет достаточно, если ты один какой-нибудь класс, попробуешь переделать так, чтобы он максимально не зависел от сети, и напишешь для него юнит тесты

2024-03-15 19:23 UTC, galinabykova commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/Manager.java
> +    private class MasterWorker implements Runnable {
Мне это кажется не очень удобным, просто потому что во вложенном классе много кода, и его так не очень удобно читать, но тесная связь тут действительно есть, так что тут на твоё усмотрение) можешь вынести это класс или не выносить

2024-03-15 19:42 UTC, galinabykova commented on task_2_1_2/src/test/java/kozlov/kirill/UnitTest.java
Кстати, если у тебя сокеты не создаются как-то совсем хаотично в классе, их можно для юнит тестов замокать, как вот тут в ответе
https://stackoverflow.com/questions/55294241/mocking-socket-getoutputstream-for-testing-java
Есть всякие библиотеки для моканья в юнит-тестах, например, Mockito, которым можно сказать, что вот если в этом тесте будет вызван метод Lya, пусть он вернёт строчку "Mya" (без вызова настоящего метода Lya). Их широко используют, когда нужно протестировать компоненты, достающие информацию из баз данных, но и для сокетов должна подойти. Мне кажется, ты будешь долго разбираться с ней (я долго с ней разбиралась, потому что на первых порах она, ну очень непривычна), и в этой лабе тебе полезнее что-то своё написать, но можешь посмотреть и использовать, если интересно

2024-03-16 05:28 UTC, KozlovKV commented on task_2_1_2/src/test/java/kozlov/kirill/UnitTest.java
Встречался я с Mockito, когда одному человеку ДЗ для курса Skill Factory java-тестировщика делал... Я не смог его поставить 😅

2024-03-16 06:42 UTC, KozlovKV commented
Полностью отделили создание сервера (`Gateway` и всё, что он продуцирует) от создания воркеров (создал `WorkersFactory`). Теперь единственное, что связывает эти компоненты - мультикаст-порт. От этого избавиться уже никак не смогу и не вижу в этом проблемы (если представить реальный режим работы приложения, то мы двумя командами запускаем фабрику и сервер, передавая первой аргументами мультикаст IP и всё прочее, а второму - порт мультикаста. 

Идеальный вариант доработки такой архитектуры - сделать фабрику также сервером, который будет создавать вокеров, принимая команды из сети. Если вдруг откуда возникнет много свободного времени, может сделаю это

2024-03-16 15:35 UTC, galinabykova requested changes
Вау, код стал намного более читаемый и понятный. Ты проделал большую работу, молодец! Оставила пару незначительных комментариев к текущей версии

2024-03-16 15:35 UTC, galinabykova commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/data/TaskData.java
> +    public ArrayList<TaskData> splitTaskData(int count) {
Круто, что ты вынес эту функцию из Менеджера. Но вот тут, мне кажется, ей немного не место. Объекты, которые гоняются по сети, обычно не нагружают бизнес-логикой. Мне кажется, что это нарушает принцип единственности ответственности. Основная ответсвенность таких классов - описывать формат передаваемых данных, в ряде случаев в них можно добавить валидацию. Разделение задач в пакете data крайне неожиданно.

2024-03-16 15:35 UTC, galinabykova commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/multicast/DatagramUtils.java
> +final public class DatagramUtils {
ещё можно добавить приватный конструктор, чтобы сохранить твою идею с запретом создания объектов

2024-03-16 15:50 UTC, KozlovKV commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/multicast/DatagramUtils.java
> +final public class DatagramUtils {
А, то есть `final` самого по себе не хватит?.. Ладно, сейчас исправлю. Почему бы разработчикам не добавить для таких случаев `static`-классы...

2024-03-16 17:31 UTC, KozlovKV commented
Вот сейчас вообще не смешно было... Сначала отображалось здесь, что билд якобы зафэйлился. Я вроде бы нашёл причину и начал фиксить. С болью починил, а сейчас вижу, что потом каким-то образом фэйл с билда пропал...

Ладно, зато баг объективно был и теперь архитектура стала ещё лучше: за создание воркеров теперь отвечает не фабрика из одного статического метода, а класс соответствующего пула

2024-03-17 16:46 UTC, KozlovKV commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/Manager.java
> +            new Thread(new Worker(socket, taskData.numbers()), "Worker").start();
Как приятно, что совсем недавно этот вопрос решился)

2024-03-18 04:15 UTC, galinabykova commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/multicast/DatagramUtils.java
> +final public class DatagramUtils {
final - это запрет наследования, но static были бы удобны, да

2024-03-18 11:58 UTC, galinabykova requested changes

2024-03-18 11:58 UTC, galinabykova commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/server/TaskManager.java
> +public class TaskManager implements Callable<Optional<TaskResult>> {
подскажи, пожалуйста, зачем тут вот этот интерфейс, что-то я по коду не могу разобраться

2024-03-18 11:58 UTC, galinabykova commented on task_2_1_2/src/test/java/kozlov/kirill/SimpleIntegrationTest.java
> +        pool.launchWorkers(TEST_PORT + 1, 100);
у тебя вот этот метод возвращает чиселку, кажется, здесь можно проверить некоторое предварительное условие, чтобы быть уверенным, что проблема будет именно в тесте, а не тут. Может, проверить, что создалось ровно 100 воркеров или, что создался хотя бы 1

2024-03-18 18:09 UTC, KozlovKV commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/server/TaskManager.java
> +public class TaskManager implements Callable<Optional<TaskResult>> {
Хах. А это легаси от того, что когда-то это был `MasterWorker`, который запускался в потоке. В целом, сейчас смысла в этом никакого - уберу

2024-03-18 18:11 UTC, KozlovKV commented on task_2_1_2/src/test/java/kozlov/kirill/SimpleIntegrationTest.java
> +        pool.launchWorkers(TEST_PORT + 1, 100);
Вообще, проблема была действительно в этом месте, но не в том, что они не создавались, тогда бы клиент получал бы ответ о недоступности воркера. Проблема возникала по совершенно мутной и непонятной причине конфликта адресов. А учитывая, что потом проблема чуть ли не сама исчезла, я теряюсь в догадках

2024-03-19 04:14 UTC, galinabykova commented on task_2_1_2/src/test/java/kozlov/kirill/SimpleIntegrationTest.java
> +        pool.launchWorkers(TEST_PORT + 1, 100);
Действительно загадочно

2024-03-20 12:37 UTC, KozlovKV commented
Такс... Вроде добавил обработку ситуации поломки воркера во время расчёта, но возникают проблемы с тестированием ситуации восстановления подсчёта с новым воркером

Также добавил несколько новых типов исключений для парсинга и сокетов и наконец сделал их более умную обработку в местах, где мы пытаемся получить данные через сокеты с парсингом

Вроде бы на этом всё. Теперь буду стиль править и, возможно, ещё пару юнит-тестов добавлю (хотя так влом уже, если честно)

2024-03-21 15:16 UTC, galinabykova approved these changes
Оставила несколько комментариев, но это так мелочь. Ты проделал большую работу, всё, что нужно, по этой лабе потрогал, так что апрувлю

2024-03-21 18:18 UTC, KozlovKV commented on task_2_1_2/src/main/java/kozlov/kirill/sockets/multicast/MulticastManager.java
> +        }
Ой... А откуда оно там взялось?.. Видимо, осталось со времён ранних тестов, где я хотел, чтобы прога жёстко умирала при ошибке. Исправлю. Скорее всего там имеет смысл просто выводить сообщения об ошибке

2024-03-26 05:34 UTC, KozlovKV commented
Оказалось, там всё же был неболльшой баг. Теперь все тесты проходят. А ревью запросил, чтобы была возможность мёрдж провести

2024-03-26 06:11 UTC, galinabykova approved these changes

2024-03-27 02:07 UTC, merged