task_2_2_1
KozlovKV/OOP pull request #15
Opened 2024-04-06 14:08 UTC by KozlovKV

Привет! Вот первая версия.

По ощущениям, она уже почти то, что нужно в итоге - добавить тестов и докстрингов, проработать обработку возможных прерываний (которых тут будто бы и быть не должно) - и всё. Но возможно я что-то и совсем не так сделал

В качестве логики завершения рабочего дня выбрал такую:
- Пекарям отправляется сообщение о возможности завершить рабочий день
- Пекари завершают готовку последнего принятого заказа и передают его на склад, сообщая пиццерии о завершении работы
- Курьерам отправляется сообщение о возможности завершить рабочий день
- Курьеры развозят все заказы из багажника и со склада, после чего завершают работу

2024-04-06 17:59 UTC, galinabykova requested changes
Решение очень хорошее) для мягкого дедлайна нужны тестики ещё (пройти порог)

2024-04-06 17:59 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +    public int size() {
меня смущает этот метод, потому что его результат по сути почти нельзя использовать, так как после разблокирования блокировки результат может быть некорректен

2024-04-06 17:59 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +    public boolean isEmpty() {
на результат этого метода, кажется, тоже нельзя полагаться

2024-04-06 17:59 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +    public ArrayList<T> getListCopy() {
и на результат этого метода тоже нельзя полагаться

2024-04-06 17:59 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/pizzeria/data/Setup.java
> +    ArrayList<Order> orders
вот тут непонятно, зачем orders, если заказы завершаются всегда перед закрытием пиццерии

2024-04-06 17:59 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +public class OwnBlockingQueue<T> {
кажется, ты используешь таймауты, чтобы не ждать вечно заказы после закрытия пиццерии. Как вариант можно было сделать метод для закрытия очереди, после которого все poll возвращались с empty

2024-04-07 03:57 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/pizzeria/data/Setup.java
> +    ArrayList<Order> orders
К закрытию будут исполнены только все принятые пекарями до сигнала подготовки к закрытию заказы, то есть какие-то непринятые к исполнению заказы могут остаться

2024-04-07 04:01 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/pizzeria/data/Setup.java
> +    ArrayList<Order> orders
Поняла)

2024-04-07 04:45 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +public class OwnBlockingQueue<T> {
Отвечу тут сразу на все комменты выше. 

У меня было 2 варианта: как препятствовать бесконечному опросу при закрытии:
1. Ввести какие-то логические блокировки (не путаем с локами) ) в класс очереди на добавление и изъятие элементов (первое будто бы не нужно, но для единообразия можно сделать), чтобы после них как раз все попытки добавления/взятия падали с особым возвратом
2. Делегировать использующему очередь обязанность решать, когда очередь переходит в (полу-)неизменяемое состояние. Методы для получения копии очереди и размеров ненадёжны, но дают то, чего я от них желаю в случае, если я уверен, что добавляться больше уже ничего не будет. То есть я могу использовать их там, где делаю это сейчас, за счёт того, что я гарантирую, например, непоступление новых заказов на склад после того, как пекари закончили свою работу. Ну и на самом деле в блокирующей очереди из Java тоже есть метод `remainingCapacity`, у которого просто в документации написано, что возвращённое им значение ненадёжно.   То есть также могу написать в документации "*Use it at your own risk*" - и всё будто бы неплохо

Выбор между этими вариантами мне не очень принципиален, хотя второй кажется более универсальным и простым. Что скажешь насчёт обоих?

2024-04-07 04:46 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +public class OwnBlockingQueue<T> {
Хотя сейчас ещё подумал - не уверен, что второй вариант универсальнее... Он более традиционный, что ли...

2024-04-07 04:46 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +public class OwnBlockingQueue<T> {
Хотя сложно говорить о традиционности в отношении многопоточных штук XD

2024-04-07 05:19 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +public class OwnBlockingQueue<T> {
Привет, соглашусь, что второй способ более универсальный - кажется, что есть ситуации, когда ненадёжное значение всё ещё может быть полезно, но эта универсальность, как мне кажется, делает более сложной работу с этой структурой данных. В целом, приемлемый вариант написать в документации, что этот метод ненадёжен, но я бы может ещё в название это добавила, чтобы пользователь уж точно заметил, что тут что-то не так.

Первый вариант мне больше нравится, потому что в нём вся ответственность за многопоточку остаётся в очереди, такой код проще понимать - ты на одном уровне абстракции проверил многопоточку, а потом уже не думаешь о ней. Возможно я ещё пристрастна, потому что сама в лабе недавно использовала закрывающуюся очередь, и мне очень понравилось с ней работать. Мне кажется, такой интерфейс очереди очень хорош (это условие моей домашки):
https://gitlab.com/Lipovsky/concurrency-course/-/tree/master/tasks/sched/thread_pool?ref_type=heads#%D0%BE%D1%87%D0%B5%D1%80%D0%B5%D0%B4%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87

Ещё добавлю, что в какой-то степени, если я правильно поняла, у тебя всё-таки там что-то вроде спинлока с долгим сном (ты ждёшь задачу, если она не пришла за N секунд, проверяешь условие, опять ждёшь и т.д.).

2024-04-07 05:20 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +public class OwnBlockingQueue<T> {
В текущей реализации мне не нравится вот эта штука со спинлоком (можешь меня переубедить). Методы, которые можно использовать, только в определённых ситуациях, можно оставить, просто прописав это в документации

2024-04-07 10:04 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +public class OwnBlockingQueue<T> {
Переубеждать не буду - сам спинлоки не люблю очень. Правда у меня пока что есть ощущение, что добавление логической блокировки в очередь от них не позволит полностью избавиться. Но я попробую

2024-04-08 12:30 UTC, KozlovKV commented
Ну вот как-то так.

Почему я не стал использовать интеррапты? Потому что мне не очень нравится работать с классами потоков, а куда приятнее работать с самими Runnable-тасками. Плюс удобнее ловить собственное исключение и понимать, что оно было вызвано очень конкретной ситуаций

Теперь надо решить, что делать с методами ненадёжными методами очереди. Пока что один из них используется в двух местах. У меня в планах избавиться от него в одном точно, во втором возможно.

Подобие спинлока одно ещё осталось. От него тоже думаю избавиться (в TODO написал, как)

На мягкий дедлайн этого достаточно?

2024-04-08 18:08 UTC, KozlovKV commented
Теперь за контроль завершения работы одним типом работников отвечает соответствующий менеджер с `CountDownLatch`, благодаря чему в классе пиццерии нет спинлока, однако переход на такой метод обнажил race condition с зависанием курьеров в некоторых случаях. Поэтому в курьерах таки пришлось вернуться к `poll`у с таймаутом. Альтернатив такому варианту я не вижу либо альтернативы тоже дают спинлок, но в другом месте и замаскированный (если, например, мы будем после посылания сигнала окончания работы постоянно интерраптить курьеров, пока те не закончат работу)

2024-04-09 05:19 UTC, galinabykova requested changes

2024-04-09 05:19 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/pizzeria/employees/EmployeesManager.java
мне понравилась идея с менеджерами, сначала не поняла, зачем они нужны, но потом осознала, что там проблема с поступательным завершением работы поваров-курьеров, и осознала, что такой компонент действительно нужен

2024-04-09 05:19 UTC, galinabykova commented on task_2_2_1/src/test/java/kozlov/kirill/queue/QueueTest.java
> +            }
кажется, что тут можно было сначала проверить корректность isPresent через Assertions.assertTrue, а потом assertEquals

2024-04-09 05:19 UTC, galinabykova commented on task_2_2_1/src/test/java/kozlov/kirill/queue/QueueTest.java
> +            }
почему в этом классе ты решил массово использовать Assertions.fail()?

2024-04-09 05:19 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/pizzeria/employees/RunnableCourier.java
> +        while (!(aboutToFinish && warehouse.isEmptyUnreliable())) {
вот тут мне не очень понятно, почему ты проверяешь пустоту склада. Кажется, что если в какой-то момент склад будет пуст в середине дня, курьер можно воспринять это как конец рабочего дня)

2024-04-09 05:19 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/pizzeria/employees/RunnableCourier.java
> +        while (!(warehouse.isEmptyUnreliable() || isTrunkFull())) {
вот тут тоже непонятно, зачем проверка на пустоту

2024-04-09 11:35 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/pizzeria/employees/RunnableCourier.java
> +        while (!(aboutToFinish && warehouse.isEmptyUnreliable())) {
Ладно. Законы де-моргана использовать в реальном коде - идея сомнительная. На самом деле там говорится: делай пока НЕ надо завершать ИЛИ НЕ пустой склад, то есть это нужно, чтобы даже после получения сигнала о завершении работы курьер продолжил забирать заказы, пока они есть

2024-04-09 11:39 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/pizzeria/employees/RunnableCourier.java
> +        while (!(warehouse.isEmptyUnreliable() || isTrunkFull())) {
А здесь опять же на самом деле будет НЕ пустой склад И НЕ заполненный багажник, то есть если на складе что-то есть и мы ещё можем что-то взять, мы будем это делать. Если склад опустел или мы уже заполнили багажник, мы завершаем наполнение багажника и отправляемся доставлять. В целом, тут можно условие непустоты убрать, так как теперь опрос с таймаутом

2024-04-09 11:54 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +    public ArrayList<T> getListCopyUnreliable() {
Хм... Будто бы это делает реализацию очереди ещё более специфичной, но в целом, можно, конечно, сделать так

2024-04-09 11:56 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +            return Optional.empty();
А это костыль, без которого try-finally использовать не получится. Либо надо возвращать не `Optional<T>`, а просто `T`, что не так хорошо

2024-04-09 12:39 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/pizzeria/employees/RunnableCourier.java
> +        while (!(aboutToFinish && warehouse.isEmptyUnreliable())) {
Аа, поняла, тут мой косяк, да) мне очень хотелось убрать isEmptyUnreliable, но теперь поняла, что оно там действительно должно быть

2024-04-09 12:42 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +    public ArrayList<T> getListCopyUnreliable() {
тут ты прав, да, с утречка мне очень хотелось убрать Unreliable любыми способами, можно не менять)

2024-04-09 12:43 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +            return Optional.empty();
а зачем возвращать Optional<T>, если у тебя всегда есть значение или бросается исключение?)

2024-04-09 15:07 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/pizzeria/employees/RunnableCourier.java
> +        while (!(aboutToFinish && warehouse.isEmptyUnreliable())) {
Да и мой косяк тоже) Обычно я не выношу не из логического выражения, так как это усложняет восприятие, а тут почему-то решил, что это неплохая идея

2024-04-09 15:45 UTC, KozlovKV commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +            return Optional.empty();
Вопрос хороший. Дело в том, что исключения появились далеко не сразу. Я проверю, оправдано ли где-то действительно использование `Optional`. Если нет, то избавлюсь от него. В прошлой лабе местами он мне очень понравился, но, пожалуй, тут он будет излишним

2024-04-11 14:39 UTC, KozlovKV commented
Совсем немного почитал про логгирование. Этого хватило, чтобы на коленке собрать что-то через `log4j`, а не на базовом `JUL`, однако не чувствую, что преисполнился в логгировании.

Может есть у тебя на примете какая-нибудь статья хорошая на эту тему?

2024-04-11 17:48 UTC, galinabykova commented
> Совсем немного почитал про логгирование. Этого хватило, чтобы на коленке собрать что-то через `log4j`, а не на базовом `JUL`, однако не чувствую, что преисполнился в логгировании.
> 
> Может есть у тебя на примете какая-нибудь статья хорошая на эту тему?

Привет, я посмотрела твой код, мне показалось, что ты вполне преисполнился) 
Мне вот эта статья понравилась, вроде не сильно сложная, но основные вещи затрагивает, но я её так быстро нагуглила (и даже прочла)
https://betterstack.com/community/guides/logging/how-to-start-logging-with-java/#5-be-descriptive-and-include-contextual-information

2024-04-11 18:45 UTC, galinabykova requested changes
Всё хорошо, добавь ещё png с UML и всё)

2024-04-11 18:45 UTC, galinabykova commented on task_2_2_1/src/main/java/kozlov/kirill/queue/OwnBlockingQueue.java
> +            throw new ProhibitedQueueActionException();
не уверена, что вот тут ты используешь исключение не в исключительной ситуации. Переделывать не надо (иначе надо будет Optional возвращать), просто заметила, решила написать

2024-04-13 13:09 UTC, KozlovKV commented
Очень-очень больно строить UML-ки для больше, чем пяти классов... Когда у меня сбилась сетка почти на финале, я не выдержал, так что пусть будет такая. Тут не совсем все связи отражены, но большая часть есть и суть работы они отражают

2024-04-14 07:25 UTC, galinabykova approved these changes
там осталось небольшое замечание reviewdog, но это так мелочи. UML получилась понятная)

2024-04-14 10:29 UTC, merged