task_2_3_1
KozlovKV/OOP pull request #16
Opened 2024-04-26 05:12 UTC by KozlovKV

Пока совсем-совсем сыро, но сама змейка уже есть

2024-04-26 19:15 UTC, KozlovKV commented
Очень странно работают инструкции в `build.gradle` - версия Java, которая прежде нормально ставилась, теперь ставиться не хочет...

2024-04-27 13:36 UTC, KozlovKV commented
А, вот ещё какой вопрос возник: как тестировать view и model-view?

2024-04-27 14:58 UTC, galinabykova commented
> А, вот ещё какой вопрос возник: как тестировать view и model-view?

Вообще есть UI-тестирование, когда ты прям разбираешь свой UI и смотришь, чего там в каком-то Label, есть практически пиксельное тестирование, когда делается скрин и ты на нём пиксели сравниваешь (конечно, с помощью специальных инструментов), но нам такого не надо. Это уже не юнит тесты, и тема для отдельного изучения.

В этой лабе протестировать надо только то, для чего можно сделать unit тесты. При хорошем разделении ты вполне можешь протестировать почти всю бизнес-логику

2024-04-28 10:11 UTC, galinabykova requested changes
Привет, сразу проговорю границы своего понимания - я писала MVVM раз в жизни в большом проекте на WPF (это для C#), поэтому мало знаю, как пишут конкретно на javafx. В целом, хорошее разделение, правда обычно стараются всё по максимуму в fxml вынести (правда я не уверена, что тут это можно сделать легко)

2024-04-29 02:29 UTC, KozlovKV commented on task_2_3_1/README.md
> +View - Finite state machine, которая будет переключать сцены и выводить данные
А, окей. Просто я эти файлы скорее воспринимал как статику, что, впрочем, не очень верно. Но в любом случае, этот план я писал ещё до того, как начал изучать, как там вообще всё работает в JavaFX

2024-04-29 02:31 UTC, KozlovKV commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model_view/GameController.java
И ещё вопрос: а смогу ли я с таким вариантом сделать изменение размера поля, потому что теоретически, я такой вариант рассматриваю (хотя вообще не факт, что успею до этого дойти)

2024-04-29 03:56 UTC, galinabykova commented
> > Привет, сразу проговорю границы своего понимания - я писала MVVM раз в жизни в большом проекте на WPF (это для C#), поэтому мало знаю, как пишут конкретно на javafx. В целом, хорошее разделение, правда обычно стараются всё по максимуму в fxml вынести (правда я не уверена, что тут это можно сделать легко)
> 
> Насколько я понял, хотя не уверен в верной интерпретации, основное отличие от MVVM в размыкании цикла связей. В MVC у нас каждая часть взаимодействовала с каждой, тогда как в MVVM model и view связываются только с view-model, а он уже взаимодействует с ними обоими

Ага, неверно выразилась, имела ввиду, что все детали представления (кнопочки, их цвета, списки и т.д.) стараются по максимуму в fxml вынести

2024-04-29 03:57 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model_view/GameController.java
Если размер задаётся в начале игры - да. Если в процессе меняется, сложно, да

2024-04-29 04:41 UTC, KozlovKV commented on task_2_3_1/src/main/resources/kozlov/kirill/snake/game-scene.fxml
Нашёл [класс TableView](https://openjfx.io/javadoc/20/javafx.controls/javafx/scene/control/TableView.html), но если честно, мне кажется его использование менее удобным, чем тот вариант с GridPane, который использую я. Вдобавок, то дополнтиельных списков это вроде как избавиться не позволит (а то и сделает их неудобнее), так что можно мне также оставить GridPane, но просто описание стилей вынести в CSS, а функции, тесно связанные со стилями, в отдельный View-класс?

2024-04-29 04:41 UTC, KozlovKV commented on task_2_3_1/src/main/resources/kozlov/kirill/snake/game-scene.fxml
Насчёт текстовых полей понял. Перейду на такой вариант. Хотя и его смысл для меня несколько загадочен. Ведь задавая `fx:id` Для самого `Label`, мы также проводим биндинг, разве нет?

2024-04-29 04:55 UTC, galinabykova commented on task_2_3_1/src/main/resources/kozlov/kirill/snake/game-scene.fxml
Да, можно, я тоже способа лучше, как это сделать) Про текстовые поля - это был минимальный пример, обычно биндятся не значения в элементах UI (как в "${qu.text}"), а какие-то свойста модели. Биндинг - это связывание, когда ты говоришь, что значение этой переменной будет меняться каждый раз, когда меняется значение другой переменной, и дальше это изменение происходит без тебя. Механизм тяжёлый, но делающий управление сильно более простым.

Это более заметно на всяких окошках настроек. Например, у тебя есть окошко настроек перед игрой, в котором задаётся длина поля. Если делать это без связывания, то тебе надо будет на каждый компонент вешать callback с изменением соответствующего поля модели. А можно сделать биндинг, и тогда при изменении значения в текстовом окне, будет меняться поле модели автоматически. Это будет одна строчка в fxml. Когда параметр один, это незаметно, но если у тебя их будет штук 20, это существенно

2024-05-02 12:50 UTC, KozlovKV commented
И ещё вопрос насчёт тестов. Получается, из трёх компонентов нам надо тестировать только view-model, так как остальные связаны с UI?

2024-05-02 17:13 UTC, KozlovKV commented
Ух... А я только начал немного любить JavaFX. Почему я не могу поставить версию Java для сборки на Гитхабе на 19-ю?.. Причём я и прежде несколькими способами пытался. На всех прежних проектах ставилась даже 21-я, а тут пишет, что не может найти toolchain

2024-05-03 04:36 UTC, galinabykova commented
> И ещё вопрос насчёт тестов. Получается, из трёх компонентов нам надо тестировать только view-model, так как остальные связаны с UI?

я предполагала, что только model, а view-model связана с ui. Нет?

2024-05-03 05:00 UTC, KozlovKV commented
> > И ещё вопрос насчёт тестов. Получается, из трёх компонентов нам надо тестировать только view-model, так как остальные связаны с UI?
> 
> я предполагала, что только model, а view-model связана с ui. Нет?

Ой, да. Я имел ввиду как раз его. 😅

2024-05-03 05:04 UTC, galinabykova commented
> Тесты после переделки падают из-за несовместимости, хех. Чуть позже пофиксю. Выделил из model-view игры часть, относящуюся сугубо ко view.
> 
> Добавил сцену с настройками и модифицировал модуль model для возможности работы с ним отовсюду. В итоге понял, что какой-то менджер нам тут не нужен. Вполне себе хватит простого enum'а с полями в виде фрагментов модели, реализующими особый интерфейс. Как мне кажется, достаточно удачное и удобное архитектурное решение. Правда есть подозрение, что я себе ощутимо усложнил тестирование
> 
> Ближайшие планы такие:
> 
> * Добавить валидаторы для полей в настройках (сейчас там можно что угодно ввести)
> * Добавить сохранение настроек в JSON, чтобы они не сбрасывались между запусками
> 
> В целом, возможно, хотелось бы на этом из фич остановиться, но вопрос, будет ли этого достаточно?

Да, фич достаточно)

2024-05-03 06:23 UTC, galinabykova requested changes
с основными особенностями ui ты разобрался, добавлю ещё, что в каких-нибудь мобилках и wpf связывание чаще всего прописывается прямо в аналоге fxml, хотя и не всегда.Твоя идея с enum очень сильно напомнила мне depencyInjection, хотя обычно этот механизм используют для других целей, интересно, что ты к этому пришёл сам. В общем, по javafx замечаний нет, можешь там больше ничего не менять (если сам не захочешь, конечно).

Ожидаю от тебя ещё тестики и выделение некоторых частей GameModel в отдельные классы. Сейчас, к сожалению, не смогу уделить много времени разбирательством с gradle build, немного потыкалась, не вышло разобраться, что там не так. Но у меня на ноутбуке твой код собирается, так что если совсем не будет собираться, я у себя локально посмотрю покрытие

2024-05-03 06:23 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model_view/GameController.java
> +        scores.setText(gameModel.getScores().toString());
мне кажется, что scores тоже можно было бы сделать через связывание, но в твою реализацию это плохо ложится, так что не надо)

2024-05-03 06:23 UTC, galinabykova commented on task_2_3_1/src/main/resources/kozlov/kirill/snake/settings-scene.fxml
> +        <Insets bottom="20.0" left="20.0" right="20.0" top="20.0"/>
есть ещё особенность с тем, что обычно при вёрстке стараются указывать относительные размеры, чтобы при растягивании и прочих странных штуках смотрелось норм, но тут и жёсткий размер норм смотрится

2024-05-03 06:23 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model_view/GameController.java
мне кажется, лучше бы называть классы как *ViewModel, Немного просто сбивает с толку, потому что есть MVC

2024-05-03 06:47 UTC, KozlovKV commented on task_2_3_1/src/main/resources/kozlov/kirill/snake/settings-scene.fxml
> +        <Insets bottom="20.0" left="20.0" right="20.0" top="20.0"/>
И плюс я запретил изменение размеров окна)

Может быть потом это изменю, но пока не уверен

2024-05-03 07:24 UTC, galinabykova commented on task_2_3_1/src/main/resources/kozlov/kirill/snake/settings-scene.fxml
> +        <Insets bottom="20.0" left="20.0" right="20.0" top="20.0"/>
а, точно)

2024-05-03 07:42 UTC, KozlovKV commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/GameModel.java
> +    private final LinkedList<Point> apples = new LinkedList<>();
Да, сейчас тут расширяемость почти никакая. У меня уже и прежде была мысль разделить игровую модель на большее количество классов. Должно будет стать сильно приятнее читать и расширять

2024-05-04 06:49 UTC, KozlovKV commented
Вынес змейку и набор яблок в отдельные класс вместе со специфичными для них методами. Разделение логики стало в разы приятнее. В какой-то момент змейка и яблоки даже были полностью независимыми модулями, но...

Потом я понял, что для по настоящему мощной расширяемости необходимо, чтобы змейка и набор яблок могли знать информацию обо всём поле (точнее, о том, какие клетки должны их убить и на каких можно появиться соответственно), поэтому пришлось сделать обратную связку с классом игровой модели. Зато теперь достаточно легко теоретически пройдёт добавление новых типов яблок и змеек либо вообще каких-то других объектов. В частности, мне интересно было бы сделать возможность выбора разных уровней.

Представляется мне это так: файлик содержит разметку поля со стенами и стартовой позицией змейки. Игровая модель берёт из настроек путь к этому файлику и парсит его. Создаётся игровое поле нужного вида со стенами и прочими штуками, затем модель сможет делиться этим полем с игровыми объектами вроде змеек, чтобы те знали, куда идти можно, а куда нет. Для этой фичи имеет смысл также вынести сущность поля в отдельный класс, который будет хранить статические параметры поля. Хотя сейчас интеграция этой фичи стала сильно проще, не уверен, что доберусь до неё - итак надо ещё кучу тестов написать + не очень я люблю игры делать, если честно + другие предметы (хотя задумка тем не менее очень интересная, самому было бы любопытно её реализовать). В общем, как минимум мыслями на этот счёт поделился и общий алгоритм реализации описал

2024-05-04 09:47 UTC, galinabykova requested changes
Всё хорошо, остались тестики и документация)

2024-05-04 09:47 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/ApplesList.java
> +    public enum Type {
а это где-то используется?

2024-05-04 09:47 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/ApplesList.java
> +    private final LinkedList<Point> list = new LinkedList<>();
интересно, что тут ты хранишь LinkedList, а в GameModel List

2024-05-04 09:47 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +    public int getListCollision(List<Point> list) {
не забудь тут в документации прописать, что значит -1) можно даже сделать соответствующее статическое поле, с мнемоникой код, который использует эту функцию, будет понятнее

2024-05-04 09:47 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +            if (equals(list.get(i))) {
какое тут будет сравнение?

2024-05-04 10:38 UTC, KozlovKV commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/ApplesList.java
> +    public enum Type {
Нет 😅

Была мысль сделать уже сразу яблоки разных цветов, но до этого так и не добрался. И не доберусь наверное - не самая интересная задача.

Уберу

2024-05-04 10:40 UTC, KozlovKV commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +            if (equals(list.get(i))) {
То есть?

Если я верно понял вопрос, то будет использоваться автосгенерированное `lombok`ом сравнение точки по координатам. Это обеспечивает аннотация `@Data`

2024-05-04 15:16 UTC, KozlovKV commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +    public int getListCollision(List<Point> list) {
Решил для чистоты перейти на `Optional` )

2024-05-04 16:33 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +            if (equals(list.get(i))) {
Ага, хорошо)

2024-05-05 06:31 UTC, KozlovKV commented
Ну вроде бы всё. Из чего-то нового - добавил вывод сообщений-подсказок при невалидном вводе настроек.

Тесты покрывают классы модели достаточно неплохо, но билд всё ещё не проходит (

По стилю осталось одно странное замечание к именам полей класса точки, которое я хз, как фиксить да и надо ли

2024-05-06 07:53 UTC, galinabykova requested changes
всё-таки исправь замечание)

2024-05-06 07:53 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +    Integer x;
судя по паттерну, ему не нравится, что символ один всего
[a-z][a-z0-9] вот тут

2024-05-06 10:08 UTC, KozlovKV commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +    Integer x;
А я пытался назвать из `xAxis` и `yAxis`, но не помогло

2024-05-06 10:09 UTC, KozlovKV commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +    Integer x;
Хотя сейчас ещё раз попробую

2024-05-06 10:13 UTC, KozlovKV commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +    Integer x;
Хах, ну ладно. Имена `axisX` и `axisY` он уже принял

2024-05-06 13:22 UTC, merged