task_2_3_1
KozlovKV/OOP pull request #17
Opened 2024-05-15 13:28 UTC by KozlovKV

Привет)

Начну делать здесь пометки о сделанном и оставшемся.

Что сейчас сделал:
- Создал отдельные класс для поля и интерфейс, через который оно будет взаимодействовать с другими игровыми объектами для получения данных о их клетках
- Создал класс менеджера змейки и реализовал хаотичную змейку, которая с вероятностью 0.8 движется прямо либо равновероятно поворачивает влево/вправо
- Немного поменял логику отрисовки, что сделало код проще (ну и в других местах за счёт класса поля код стал лучше, особенно сама `GameModel`)

Что собираюсь сделать:
- Выделить ИИ змейки в отдельный класс типа `SnakeAi`, который будет решать, куда змейке двигаться. В таком случае `ComputerSnakeManager` будет отвечать за создание/воскрешение змеек и балансировку их скорости. Это улучшит соблюдение солида и будет удобно для добавления других стратегий поведения
- Добавить змейку охотника (пожиратель, о котором написал в `README` сейчас мне кажется не самой удачной идеей. Будто бы тогда балансировка сложности очень сильно возрастает)
- Добавить возможность создавать поля с препятствиями. Писал об этом и раньше, а теперь задача станет ещё проще

2024-05-16 06:15 UTC, galinabykova reviewed
Посмотрела текущие правки, значимых замечаний нет, всё хорошо)

2024-05-16 06:15 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/ComputerSnakeManager.java
> +        int percent = new Random().nextInt(100);
интересно, что ты решил выбирать случайное из 100, а не из 10, хотя последний 0 вроде ни на что не влияет, так как все числа кратны 10

2024-05-16 12:48 UTC, KozlovKV commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/ComputerSnakeManager.java
> +        int percent = new Random().nextInt(100);
Ну это пока совсем кривая штука 😅

Потом будет сильно по другом) ( ну или не очень сильно XD )

2024-05-18 10:11 UTC, KozlovKV commented
Разобрался с большинством TODOшек, сделав код приятнее, вынес ИИ змейки в отдельный от менеджера искусственных змеек класс, добавил змейку-охотника. Насчёт кастомных полей теперь в некоторых сомнениях. Дело в том, что в текущем сэтапе - с двумя вражескими змейками, умной и хаотичной - итак уже контроллировать всю ситуацию на поле весьма непросто, так что не уверен, что механика стен сделает игровой опыт лучше.

Оставшиеся действия:
- Переписать часть тестов и добавить новые
- Обновить список настроек (хочу запретить изменение размеров поля, а дать возможность настраивать количество яблок и змеек-врагов) 
- Немного стиль поменять
- ВОЗМОЖНО немного изменить логику смерти, потому что сейчас головы у змеек не убивающие, что может порождать странные ситуации (что, впрочем, я осмелюсь назвать не багом, а фичей)

2024-05-19 09:22 UTC, galinabykova requested changes
Всё хорошо, для плюс балла будет достаточно, если просто reviewdog поправишь, но если хочешь что-то ещё сделать - здорово)

2024-05-19 09:22 UTC, galinabykova commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +            Math.pow((other.axisX - axisX), 2) + Math.pow((other.axisY - axisY), 2)
интересно, что ты тут выбрал евклидову метрику, хотя с точки зрения игры манхеттенская как будто выигрышнее

2024-05-19 10:28 UTC, KozlovKV commented on task_2_3_1/src/main/java/kozlov/kirill/snake/model/game/Point.java
> +            Math.pow((other.axisX - axisX), 2) + Math.pow((other.axisY - axisY), 2)
Да, я о ней думал, технически, разницы в преодолеваемом расстоянии не будет, а считать манхеттенскую куда приятнее, но тогда поведение змейки было чуть скучнее - сначала по одной прямой, потом по другой, а так она будет лесенку рисовать, стремясь сразу к голове игрока

2024-05-21 16:04 UTC, galinabykova approved these changes
мне понравилось, как ты переделал валидацию, получилось красиво и аккуратно)

2024-05-21 16:09 UTC, merged