task_1_1_1
KozlovKV/OOP pull request #5
Opened 2023-09-10 06:20 UTC by KozlovKV

2023-09-10 12:41 UTC, galinabykova requested changes
Все предупреждения от reviewdog (см. во вкладке Files changed) должны быть решены за исключением тех, которые вы можете аргументированно оспорить.
[https://github.com/shadrina/OOP/pull/3](url)

2023-09-10 12:41 UTC, galinabykova commented on .gitignore
У тебя тут игнорируется папка .idea по относительному пути, то есть в корневой папке репозитория, а папка task_1_1_1/idea, которую, скорее всего, ты хотел проинорировать, не игнорируется. Вообще .idea не обязательно игнорить, но вот .gradle и build надо
[https://stackoverflow.com/questions/17200831/should-the-gradle-folder-be-added-to-version-control](url)

2023-09-10 12:41 UTC, galinabykova commented on task_1_1_1/.gradle/8.2/fileHashes/resourceHashesCache.bin
.gradle используется для кэша, поэтому её можно спокойно добавить в .gitignore

2023-09-10 14:45 UTC, KozlovKV reviewed
Вроде больше замечаний по стилю кода не осталось

2023-09-11 06:49 UTC, galinabykova requested changes
При очной сдаче хотелось бы услышать, почему в текущей версии твоей реализации ты решил использовать clone для массива.

2023-09-11 06:49 UTC, galinabykova commented on task_1_1_1/src/main/java/org/example/HeapSorter.java
> +        int left = i * 2 + 1;
мне кажется, left не очень удачное название, непонятно, что это индекс и что левый здесь значит "левый потомок". Предлагаю назвать переменную leftChildIndex

2023-09-11 06:49 UTC, galinabykova commented on task_1_1_1/src/main/java/org/example/HeapSorter.java
> +            if (left + 1 < this.heapSize
я бы сделала отдельную переменную rightChildIndex или что-то в этом роде, чтобы сразу было понятно, что это за +1

2023-09-11 06:49 UTC, galinabykova commented on task_1_1_1/src/main/java/org/example/HeapSorter.java
> +package org.example;
пакетам лучше давать осмысленные названия

2023-09-11 06:49 UTC, galinabykova commented on task_1_1_1/src/main/java/org/example/Main.java
> +        hs.heapsort(new int[] {4, 8, 1, -5, 6});
мне кажется, что heapsort могла бы сразу возвращать отсортированный массив или менять прямо входной, чтобы можно было отсортировать массив в одну строчку. Если нужно будет отсортировывать много массивов в одной функции, будет очень неудобно читать код с интерфейсом, который реализован сейчас (когда три строчки - это по сути одно простое действие)

2023-09-11 12:54 UTC, KozlovKV commented on task_1_1_1/src/main/java/org/example/Main.java
> +        hs.heapsort(new int[] {4, 8, 1, -5, 6});
Решил оставить конструктор пустым, чтобы можно было использовать один сортировщик многократно. В основной метод сортировки добавил возврат отсортированного массива.

2023-09-11 12:55 UTC, KozlovKV commented on task_1_1_1/src/main/java/org/example/HeapSorter.java
> +package org.example;
Пока что не совсем понимаю логику именования пакетов. Обязательно ли оставлять часть `org`? Вместо `example` дал более осмысленное имя

2023-09-11 14:51 UTC, galinabykova commented on task_1_1_1/src/main/java/org/example/HeapSorter.java
> +package org.example;
Про имена пакетов можешь почитать здесь
[https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html](url)
Текущее имя подойдёт, исправлять не надо

2023-09-11 16:37 UTC, galinabykova commented on task_1_1_1/src/main/java/org/example/Main.java
> +        hs.heapsort(new int[] {4, 8, 1, -5, 6});
я бы наверно ещё убрала getArr, т. к. оно теперь не нужно, и переделала тесты, но ты можешь это не делать, эта лаба не про это

2023-09-12 16:30 UTC, galinabykova approved these changes

2023-09-13 04:10 UTC, merged