task_1_1_2
KozlovKV/OOP pull request #6
Opened 2023-09-12 13:37 UTC by KozlovKV

Не совсем были ясны некоторые моменты в генерации строки для полинома. В итоге постарался учесть все возможные нюансы кроме опускания коэффициента, равного `1`.

2023-09-21 07:35 UTC, galinabykova requested changes

2023-09-21 07:35 UTC, galinabykova commented on task_1_1_2/src/main/java/org/polynom/Polynomial.java
> +    public String toString() {
есть аннотация override, которой можно отмечать переопределённые методы. Она служит предупреждением для компилятора, чтобы он проверил, является ли этот метод действительно переопределением

2023-09-21 07:35 UTC, galinabykova commented on task_1_1_2/src/test/java/org/polynom/PolyTest.java
добавь, пожалуйста, тест на вычитание полинома из самого себя

2023-09-22 07:53 UTC, galinabykova requested changes

2023-09-22 07:53 UTC, galinabykova commented on task_1_1_2/src/test/java/org/polynom/PolyTest.java
> +    void voidEqual1() {
здесь тоже нужны осмысленные названия

2023-09-22 07:53 UTC, galinabykova commented on task_1_1_2/src/main/java/org/polynom/Polynomial.java
> +    public boolean equals(Object obj) {
если ты переопределяешь equals, нужно переопределять hashCode
https://javarush.com/groups/posts/3957-kofe-breyk-168-zachem-pereopredeljatjh-metodih-equals-i-hashcode-v-java

2023-09-23 06:33 UTC, KozlovKV commented on task_1_1_2/src/main/java/org/polynom/Polynomial.java
> +    public boolean equals(Object obj) {
Ой, в первый раз не особо внимательно прочёл статьи... Исправляюсь

2023-09-24 18:24 UTC, galinabykova requested changes

2023-09-24 18:24 UTC, galinabykova commented on task_1_1_2/src/main/java/kozlov/kirill/polynom/Polynomial.java
> +        if (this.length() != otherP.length()) {
кажется, что, если obj не полином и не массив, тут может случиться что-то вроде this.length() != null.length()

2023-09-25 04:23 UTC, galinabykova approved these changes

2023-09-25 04:23 UTC, galinabykova commented on task_1_1_2/src/test/java/kozlov/kirill/polynom/PolyTest.java
> +    void testMainRunning() {
здесь можешь не исправлять, но в дальнейшем не делай такой тест. Точку входа ты можешь затолкать прямо в Polynomial, и тогда у тебя не должно слишком сильно просесть покрытие из-за main. Если ты не можешь пройти порог по покрытию из-за main, скорее всего что-то спроектировано не так, и ты можешь выделить в main функции, которые уже можно покрыть настоящими тестами.

2023-09-25 10:19 UTC, KozlovKV commented on task_1_1_2/src/test/java/kozlov/kirill/polynom/PolyTest.java
> +    void testMainRunning() {
О! Так будет в разы удобнее, спасибо 🙏

2023-09-25 10:19 UTC, merged