task_1_2_1
KozlovKV/OOP pull request #7
Opened 2023-09-30 09:08 UTC by KozlovKV

Привет! Если честно, очень не уверен, что сделал верно итераторы, поэтому решил отправить версию без всего запланированного функционала, чтобы понять, движусь ли я вообще в верном направлении.

Отдельно меня интересуют несколько моментов:
1. Надо ли переопределять метод `remove` в классах итераторов? Как я понял, он работает независимо от метода `remove` самого класса дерева и это даже нормально
2. Надо ли, чтобы работали ещё какие-то функции обхода вроде `stream().map()` / `stream().filter()` или достаточно, чтобы как сейчас работал `forEach`?

2023-10-01 16:57 UTC, galinabykova commented
> Привет! Если честно, очень не уверен, что сделал верно итераторы, поэтому решил отправить версию без всего запланированного функционала, чтобы понять, движусь ли я вообще в верном направлении.
> 
> Отдельно меня интересуют несколько моментов:
> 
> 1. Надо ли переопределять метод `remove` в классах итераторов? Как я понял, он работает независимо от метода `remove` самого класса дерева и это даже нормально
> 2. Надо ли, чтобы работали ещё какие-то функции обхода вроде `stream().map()` / `stream().filter()` или достаточно, чтобы как сейчас работал `forEach`?

Привет!
1. да, надо переопределить. Есть структуры данных, в которых будет проблематично реализовать этот метод (какая-нибудь двоичная куча на массиве, где удаление элемента ведёт к перестраиванию всей структуры), но в дереве с этим не должно быть проблем
2. достаточно `forEach`. Разобраться, как можно использовать Stream API после реализации итерирования - это задание на доп балл)

2023-10-02 06:32 UTC, KozlovKV commented
@galinabykova , отлично, значит буду реализовывать `remove` для итераторов.

И по поводу него тоже есть пара вопросов:
1. `remove` итератора должен удалять вершину из итерирования БЕЗ влияния на исходную коллекцию, верно?
2. Как поступать при вызове этого `remove`? Пропускать только саму вершину или её потомков тоже отбрасывать? (второй вариант мне кажется логичнее)

2023-10-02 06:44 UTC, galinabykova commented
> @galinabykova , отлично, значит буду реализовывать `remove` для итераторов.
> 
> И по поводу него тоже есть пара вопросов:
> 
> 1. `remove` итератора должен удалять вершину из итерирования БЕЗ влияния на исходную коллекцию, верно?
> 2. Как поступать при вызове этого `remove`? Пропускать только саму вершину или её потомков тоже отбрасывать? (второй вариант мне кажется логичнее)

1. да
2. в условии не указано, так что тут тебе нужно самому решить, какое поведение будет в твоей коллекции. Это поведение нужно заспецифицировать и, возможно, при защите я спрошу тебя, почему твоя коллекция работает именно так

2023-10-03 11:59 UTC, KozlovKV commented
Привет! Решил ещё раз проверить [документацию Java по поводу Iterator.remove()](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/Iterator.html#remove()). Там они всё же говорят, что при вызове `remove()` у итератора должен также удаляться элемент и из коллекции в целом. Пока что сделал такую реализацию.

При вызове `remove()` у вершины происходит очистка её списка потомков и удаление вершины из списка потомков родителя. Значение вершины остаётся на месте.

2023-10-09 08:43 UTC, galinabykova requested changes

2023-10-09 08:43 UTC, galinabykova commented on task_1_2_1/src/main/java/kozlov/kirill/tree/Tree.java
> +public class Tree<T> implements Iterable<Tree<T>> {
а, поняла, у тебя Tree - это узел и ты итерируешься по узлам

2023-10-09 08:43 UTC, galinabykova commented on task_1_2_1/src/main/java/kozlov/kirill/tree/Tree.java
> +    public void remove() {
как твоя коллекция ведёт себя, если пользователь захочет удалять элемент в процессе итерирования?

2023-10-09 08:43 UTC, galinabykova commented on task_1_2_1/src/main/java/kozlov/kirill/tree/Tree.java
> +public class Tree<T> implements Iterable<Tree<T>> {
я бы, наверно, итерировалась по элементам, оставляя все детали реализации в итераторе. Ты обдумывал такой вариант и, если да, почему от него отказался?

2023-10-10 15:18 UTC, KozlovKV commented on task_1_2_1/src/main/java/kozlov/kirill/tree/Tree.java
> +public class Tree<T> implements Iterable<Tree<T>> {
Привет. На самом деле, относительно дерева даже не рассматривал такой вариант. Сейчас подумал и решил, что, наверное, стоит оставить такой, так как это даст больше гибкости для взаимодействия с элементами при итерации (посмотреть их детей или ещё какие-то поля). Хотя, наверное, самым правильным решением будет сделать отдельный класс `Node` и добавить в него информацию, которую мы относим именно к вершинам, а в классе дерева хранить, скажем, корень. Но тогда логика сильно усложнится. Не будет возможности свободно добавлять вершины в определённым узлам дерева (вернее она будет, но сильно сложнее, чем это сделано сейчас и уже совсем не будет соответствовать примеру использования класса, который был в задании).

2023-10-10 15:30 UTC, KozlovKV commented on task_1_2_1/src/main/java/kozlov/kirill/tree/Tree.java
> +    public void remove() {
Ой, а вот тут начинается нечто странное. Если мы используем обёртку от итератора, то всё работает нормально - в итерации будут пропущены все вершины, являющиеся потомками той, в которой мы сейчас находимся по итерации. Если мы будем обращаться по другим ссылкам, ведущим на элементы дерева, и удалять их, то мы в итерации можем потерять вершину-брата/сестру. Буду думать сейчас либо завтра на паре, что с этим сделать. *Причём проблема эта, из-за использования хэш-таблицы для запоминания индексов, наблюдается только в DFS*

2023-10-11 05:44 UTC, galinabykova commented on task_1_2_1/src/main/java/kozlov/kirill/tree/Tree.java
> +    public void remove() {
Если что, тебе не обязательно думать, как исправить ситуацию, когда пользователь твоей библиотеки делает что-то некорректное. Ты можешь кинуть исключение

2023-10-12 06:53 UTC, KozlovKV commented
Создал для каждого метода итерации свой коллекцию. Теперь можно итерироваться любым методом при помощи `for (var val : Collection)`, что куда приятнее костыля, который был прежде. Также перешёл на `Iterable<T>`, как мы и обсуждали.

Для выбрасывания `ConcurrentModificationException` сделал флаг блокировки корня итерации. Как мне кажется, пусть это решение и самое простое, но в то же время и самое удобное. При попытке любой модфикации будем идти вверх до корня и, если нашли блокировку, выбрасываем исключение. Итераторы при этом будут хранить в себе корень итерации и снимут с него блокировку, когда итерация завершится.

У меня возник вот такой вопрос: можем ли мы как-то сделать метод класса `Tree` Доступным внутри `DfsTreeCollection` и `BfsTreeCollection`, не вставляее код этих классов внутри дерева. Просто метод `forceRemove` будто бы не должен быть полностью публичным, но в то же время нам в конкретных местах нужен доступ в него извне

2023-10-12 13:20 UTC, galinabykova commented
> Создал для каждого метода итерации свой коллекцию. Теперь можно итерироваться любым методом при помощи `for (var val : Collection)`, что куда приятнее костыля, который был прежде. Также перешёл на `Iterable<T>`, как мы и обсуждали.
> 
> Для выбрасывания `ConcurrentModificationException` сделал флаг блокировки корня итерации. Как мне кажется, пусть это решение и самое простое, но в то же время и самое удобное. При попытке любой модфикации будем идти вверх до корня и, если нашли блокировку, выбрасываем исключение. Итераторы при этом будут хранить в себе корень итерации и снимут с него блокировку, когда итерация завершится.
> 
> У меня возник вот такой вопрос: можем ли мы как-то сделать метод класса `Tree` Доступным внутри `DfsTreeCollection` и `BfsTreeCollection`, не вставляее код этих классов внутри дерева. Просто метод `forceRemove` будто бы не должен быть полностью публичным, но в то же время нам в конкретных местах нужен доступ в него извне

Привет, в отличие от с++ в java нет friend, но гуглится вот такая штука
https://stackoverflow.com/questions/182278/is-there-a-way-to-simulate-the-c-friend-concept-in-java

Правда для тебя, поскольку DfsTreeCollection и Tree в одном пакете, Friend Accessor будет просто лишним телодвижением. Мне кажется, что можно просто сделать forceRemove видимым в пакете  (package private). Тогда пользователи пакета не смогут его использовать, а в DfsTreeCollection и BfsTreeCollection его будет можно использовать. 

Ещё есть идея отнаследовать DfsTreeCollection и BfsTreeCollection от Tree и сделать метод forceRemove protected, но мне кажется, это так себе идея

2023-10-12 18:19 UTC, galinabykova requested changes

2023-10-12 18:19 UTC, galinabykova commented on task_1_2_1/src/main/java/kozlov/kirill/tree/Tree.java
> +    public void block() {
видимо пару методов block/unblock тоже надо скрыть от пользователя

2023-10-12 18:19 UTC, galinabykova commented on task_1_2_1/src/main/java/kozlov/kirill/tree/Tree.java
> +    public Tree<T> parent = null;
а почему это поле public?

2023-10-13 03:53 UTC, KozlovKV commented on task_1_2_1/src/main/java/kozlov/kirill/tree/Tree.java
> +    public Tree<T> parent = null;
Сделал так для доступа к ним из Коллекций. Тут везде надо бы навешать package-private, пожалуй

2023-10-14 05:34 UTC, galinabykova approved these changes

2023-10-16 11:53 UTC, merged