task_1_2_2
KozlovKV/OOP pull request #9
Opened 2023-10-21 15:30 UTC by KozlovKV

Привет! Прописал пока что не все тесты, но в остальном вроде как код готов. 

У меня есть много чего сказать насчёт востребованности наследования, интерфейсов и абстракций в этом задании, но это оставлю для очной сдачи.

2023-10-21 15:37 UTC, KozlovKV commented
Ладно... До правок стиля доберусь как-нибудь потом, а пока что надо с тестами разобраться. Может быть дело в этом, что точка запуска тестов - не корень проекта, поэтому не находится файл для загрузки параметров графа?

2023-10-22 07:03 UTC, galinabykova commented
> Ладно... До правок стиля доберусь как-нибудь потом, а пока что надо с тестами разобраться. Может быть дело в этом, что точка запуска тестов - не корень проекта, поэтому не находится файл для загрузки параметров графа?

не похоже, судя по исключению файлик он нашёл, но почему-то не смог распарсить

я думаю, исключение может бросаться в строчке 23 в Main.java
https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#parseDouble-java.lang.String-

2023-10-22 17:39 UTC, KozlovKV commented
Собрался написать тесты и решил, что не хочу дублировать код. Поэтому встаёт вопрос: а можем ли мы создать какой-то абстрактный класс тестирования, чтобы потом создать 3 мини-класса в которых укажем, что тут тестироваться во всех методах абстрактного класса должен граф на списках смежности, тут на одних матрицах, тут на других? Я пытался задать основному классу тестирования поле типа, чтобы мы могли в мини-классах указать в этом поле конкретный тип, но Java очень ругается на эту концепцию, а особенно на зписи вида `var graph = new this.myType<String>()`. Попытка сделать тип графа параметром класса тоже не помогла - запись вида `var graph = new T<String>()` тоже не принимается. Могу ли я вообще хоть как-то сделать желаемое? Пока что нашёл вариант с прописываем в базовом классе логики тестов, а вызове тестов из мини-классов, но проблема в том, что тогда мне для каждого базового теста нужно и обёртку писать. Всё равно выйдет строчек меньше, конечно, но уже не насктолько кардинально и элегантно

2023-10-22 20:20 UTC, galinabykova commented
> Собрался написать тесты и решил, что не хочу дублировать код. Поэтому встаёт вопрос: а можем ли мы создать какой-то абстрактный класс тестирования, чтобы потом создать 3 мини-класса в которых укажем, что тут тестироваться во всех методах абстрактного класса должен граф на списках смежности, тут на одних матрицах, тут на других? Я пытался задать основному классу тестирования поле типа, чтобы мы могли в мини-классах указать в этом поле конкретный тип, .но Java очень ругается на эту концепцию, а особенно на зписи вида `var graph = new this.myType<String>()`. Попытка сделать тип графа параметром класса тоже не помогла - запись вида `var graph = new T<String>()` тоже не принимается. Могу ли я вообще хоть как-то сделать желаемое? Пока что нашёл вариант с прописываем в базовом классе логики тестов, а вызове тестов из мини-классов, но проблема в том, что тогда мне для каждого базового теста нужно и обёртку писать. Всё равно выйдет строчек меньше, конечно, но уже не насктолько кардинально и элегантно

Привет, никогда не сталкивалась с абстрактными классами для тестирования, но у меня есть сильное подозрение, что тебе для твоей цели будет достаточно параметризированных тестов (тестов, в которые мы толкаем переменные). Так как твои классы имеют общего родителя, ты можешь писать код, который будет знать лишь то, что он работает с Graph, каждый раз подсовывая ему объекты разных классов. Это сильно несовершенный пример того, как это можно сделать
```java    
    @ParameterizedTest
    @ArgumentsSource(testArgumentsProvider.class)
    void testAdjacencyMatrixGraph(Graph<String> graph) {
        Main.readDataForGraphFromFile(graph, "input.txt");
        var result = graph.constructShortestDistances("C");
        Assertions.assertEquals(result, getPredictedMap());
    }

    static class testArgumentsProvider implements ArgumentsProvider {
        @Override
        public Stream<? extends Arguments> provideArguments(ExtensionContext context) {
            return Stream.of(
                    Arguments.of(new IncidentMatrixGraph<String>()),
                    Arguments.of(new AdjacencyMatrixGraph<String>())
            );
        }
    }
 ``` 
Тут мы запускаем тест testAdjacencyMatrixGraph с разными входными аргументами graph из потока из provideArguments.

2023-10-24 18:05 UTC, KozlovKV commented
Фух! Тесты написал. И отловил вдобавок благодаря ним пару ошибок, связанных с тем, что изначально писал код под неориентированный граф, а где-то на середине сделал возможность выбирать между оринетированным и нет для того, чтобы считать пути с отрицательными весами. `toString`и исключил из тестов, так как это было бы частично странно - проверять текстовый вывод целой матрицы (ну и мне немного лень прописывать ожидаемые результаты, да). Тут уже на самом деле встаёт вопрос, а нужно ли вообще текстовое представление этим графам, так как даже при отладке я пользовался методами для получения различных списков и map'ов.

И ещё... Мне проверка стиля говорит, что всё ок. Была пара замечаний, которые я исправил, поэтому скорее всего она работает, но при этом документации к каждому публичному методу не требуют. Формально всё вроде как прошло, но если необходимо, могу добавить везде доки (пока что сделал их для абстрактного графа, что логичнее, чем копипастить их для всех его наслдеников)

2023-10-24 20:08 UTC, galinabykova requested changes

2023-10-24 20:08 UTC, galinabykova commented on task_1_2_2/src/main/java/kozlov/kirill/graph/IncidentMatrixGraph.java
> +    Map<Vertex<T>, Map<Edge<T>, Integer>> incidentMatrix = new HashMap<>();
насколько я поняла, Integer здесь принимает значения 1, -1, 0 в зависимости от ориентированности ребра. Если это так, стоит завести Enum, чтобы сделать код читаемее и не нужно было держать в голове, как магическая константа чему соответствует

2023-10-24 20:08 UTC, galinabykova commented on task_1_2_2/src/main/java/kozlov/kirill/graph/AbstractGraph.java
> +    protected Map<T, Vertex<T>> vertexMap = new HashMap<>();
возможно стоит как-то иначе назвать переменную, более уникально что ли. Ты в коде несколько раз создаёшь локальные переменные с этим названием, и это слегка запутывает при чтении

2023-10-25 04:08 UTC, KozlovKV commented on task_1_2_2/src/main/java/kozlov/kirill/graph/Vertex.java
> +    public void resetDistance() {
Нет, справделиво

2023-10-25 04:44 UTC, KozlovKV commented on task_1_2_2/src/main/java/kozlov/kirill/graph/AbstractGraph.java
> +        if (getEdgeSet().isEmpty()) {
Вообще, код будет работать почти корректно даже при изменении типа графа на лету. Единственное различие - флаги возврата в `addEdge` и `removeEdge` - так что исключение кидать смысл есть

2023-10-25 09:49 UTC, KozlovKV commented on task_1_2_2/src/main/java/kozlov/kirill/graph/AbstractGraph.java
> +    public Vertex<T> removeVertex(T value) {
Прекрасная идея! Всё-таки осознание удобства абстракций приходит постепенно

2023-10-25 17:08 UTC, galinabykova approved these changes

2023-10-25 18:24 UTC, KozlovKV commented on task_1_2_2/src/test/java/kozlov/kirill/graph/GraphTest.java
> +        predicted.put("C", 0.0);
Да, понимаю. Я ведь большой граф так и оставил в файле, а прямо в тесты добавлял маленьнике по 3-4 вершины. Просто не хотелось слишком много немного различающихся инпутов записывать в отдельные файлы. А здесь у нас создаётся не граф, а таблица результатов для подсчёта длин путей

2023-10-25 18:25 UTC, merged